feat(RELEASE-936): add artifacts field to the status
konflux-ci/release-service pull request #472
Opened 2024-05-29 13:54 UTC by davidmogar

This change adds a new field to the Release status to store artifacts generated by the managed Release Pipeline.

2024-05-30 08:18 UTC, mmalina requested changes
Hopefully all the extra changes will disappear once https://github.com/konflux-ci/release-service/pull/473 is merged. I will review again once that happens.

2024-06-03 13:14 UTC, johnbieren approved these changes

2024-06-03 13:51 UTC, davidmogar commented
@mmalina Can you approve if you are ok with it now?

2024-06-03 14:11 UTC, mmalina commented
> @mmalina Can you approve if you are ok with it now?

Done. LGTM.

2024-06-03 14:12 UTC, merged