feat(RELEASE-1171): create integration test pipeline for release-servi…
konflux-ci/release-service pull request #566
Opened 2024-09-19 06:33 UTC by jinqi7

…ce repo"

2024-09-19 07:38 UTC, flacatus requested changes

2024-09-19 07:38 UTC, flacatus commented on integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
> +  name: konflux-e2e-tests-pipeline.yaml
konflux-e2e-tests-pipeline

2024-09-19 07:38 UTC, flacatus commented on integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
> +      default: 'quay.io/konflux-test-storage/release-service'
quay.io/konflux-test-storage/konflux-team/release-service

2024-09-19 07:49 UTC, jinqi7 commented on integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
> +  name: konflux-e2e-tests-pipeline.yaml
Update!

2024-09-19 07:49 UTC, jinqi7 commented on integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
> +      default: 'quay.io/konflux-test-storage/release-service'
Updated, thanks!

2024-09-19 08:56 UTC, jinqi7 commented on integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
> +        - rosa-hcp-metadata
It's already been added before "provision-rosa" task.

2024-09-24 09:23 UTC, jinqi7 commented
/retest

2024-09-24 09:49 UTC, flacatus commented on integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
> +        - rosa-hcp-metadata
I mean in the runAfter section

2024-09-24 10:02 UTC, flacatus commented
/retest

2024-09-24 10:18 UTC, jinqi7 commented on integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
> +        - rosa-hcp-metadata
Updated!

2024-09-24 11:52 UTC, flacatus commented
/retest

2024-09-25 09:41 UTC, jinqi7 commented
/retest

2024-09-25 10:32 UTC, jinqi7 commented
/retest

2024-09-25 12:27 UTC, jinqi7 commented
/retest

2024-09-25 13:53 UTC, jinqi7 commented
/retest

2024-09-25 14:00 UTC, kasemAlem commented
it's failing on the task [quality-dashboard-upload]([quality-dashboard-upload](https://console.redhat.com/application-pipeline/ns/rhtap-release-2-tenant/pipelinerun/release-service-gn7qf-dl8sb/logs/quality-dashboard-upload)) , should we create a ticket for it, @psturc  @flacatus ?

2024-09-25 14:29 UTC, jinqi7 commented
/retest

2024-09-25 14:34 UTC, kasemAlem commented
> it's failing on the task quality-dashboard-upload , should we create a ticket for it, @psturc @flacatus
okay, I see that Jing already fixed it according to [this](https://redhat-internal.slack.com/archives/C02FANRBZQD/p1727272933201259)

2024-09-25 15:07 UTC, flacatus commented
/retest

2024-09-26 02:31 UTC, jinqi7 commented
/retest

2024-09-26 05:30 UTC, jinqi7 commented
/retest

2024-09-26 10:03 UTC, jinqi7 commented on integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
> +        - name: container-image
Done

2024-09-27 08:48 UTC, flacatus commented
LGTM

2024-09-27 09:43 UTC, flacatus approved these changes

2024-09-27 09:54 UTC, jinqi7 commented
/retest

2024-09-27 11:00 UTC, jinqi7 commented
/retest

2024-09-27 12:10 UTC, jinqi7 commented
/hold
Currently there is some issue with "provision rosa" in e2e-tests repo, May meet the same issue here.

2024-09-29 06:54 UTC, jinqi7 commented
/unhold

2024-09-29 09:43 UTC, jinqi7 commented
/retest

2024-09-29 10:23 UTC, jinqi7 commented
/retest

2024-09-29 11:45 UTC, flacatus commented
/test release-service-e2e

2024-09-29 12:50 UTC, merged